apiVersion: v1
kind: Service
metadata:
  name: kafkaconnect
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version  }}
    app.kubernetes.io/part-of: worker
spec:
  type: {{ .Values.global.common.service.type }}
  ports:
    - port: {{ .Values.global.common.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version  }}
    app.kubernetes.io/part-of: worker