apiVersion: apps/v1
kind: Deployment
metadata:
  name: merlin-internal-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: api
spec:
  replicas: {{ .Values.merlininternalapi.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.merlininternalapi.maxSurge }}
      maxUnavailable: {{ .Values.merlininternalapi.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/part-of: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: api
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.common.imagePullSecrets }}
      serviceAccountName: secrets-manager
      securityContext:
        {{- toYaml .Values.global.common.podSecurityContext | nindent 8 }}
      initContainers:
        - name: awscli-secret-manager
          image: docker.io/punchh/init-container-secrets-manager:v1
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:
            - name: init-config
              mountPath: /tmp/
            - name: secret-vol
              mountPath: /mnt/
          env:
      {{- range $key, $value := .Values.merlininternalapi.initcontainer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.merlininternalapi.name }}
          securityContext:
            {{- toYaml .Values.global.common.securityContext | nindent 12 }}
          image: {{ .Values.images.merlininternalapi }}:{{ .Values.tags.merlininternalapi }}
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          volumeMounts:
            - name: secret-vol
              mountPath: /tmp/
          ports:
            - name: app
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.livenessProbe.successThreshold }}
          resources:
            {{- toYaml .Values.merlininternalapi.resources | nindent 12 }}
          env:
{{- range $key, $value := .Values.global.common.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.merlininternalapi.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: VAULT_TOKEN
      volumes:
        - name: init-config
          configMap:
            name: merlin-internal
        - name: secret-vol
          emptyDir:
            medium: Memory
