{{- if .Values.merlininternalapi.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-merlin-internal-api
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: merlin-internal-api
  minReplicas: 1
  maxReplicas: {{ .Values.merlininternalapi.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.merlininternalapi.hpa.type }}
      targetAverageUtilization: {{ .Values.global.common.hpa.targetAverageUtilization }}
{{ end }}
