{{- if .Values.jbsignupprocessor.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-jbsignupprocessor
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: jbsignupprocessor
  minReplicas: 1
  maxReplicas: {{ .Values.jbsignupprocessor.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.jbsignupprocessor.hpa.type }}
      targetAverageUtilization: {{ .Values.global.common.hpa.targetAverageUtilization }}
{{ end }}
