name: cadence
version: 0.12.1
appVersion: 0.14.1
description: Cadence is a distributed, scalable, durable, and highly available orchestration engine to execute asynchronous long-running business logic in a scalable and resilient way.
apiVersion: v1
