apiVersion: apps/v1
kind: Deployment
metadata:
  name: merlin-gateway
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: api
spec:
  replicas: {{ .Values.merlingateway.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.merlingateway.maxSurge }}
      maxUnavailable: {{ .Values.merlingateway.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/part-of: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: api
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.common.imagePullSecrets }}
    {{- if .Values.global.common.serviceAccount.create }}
      serviceAccountName: merlingateway
    {{- end }}
      securityContext:
        {{- toYaml .Values.global.common.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.merlingateway.name }}
          securityContext:
            {{- toYaml .Values.global.common.securityContext | nindent 12 }}
          image: {{ .Values.images.merlingateway }}:{{ .Values.tags.merlingateway }}
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          ports:
            - name: app
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.livenessProbe.successThreshold }}
          resources:
            {{- toYaml .Values.merlingateway.resources | nindent 12 }}
          env:
{{- range $key, $value := .Values.global.common.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.merlingateway.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: VAULT_TOKEN
