apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: redis
    role: master
  type: ClusterIP