global:
  common:
    imagePullSecrets: regcred
    pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    serviceAccount:
      create: false
    env:
      TENANT: dairyqueen
      TENANT_NAME: dairyqueen
      VAULT_HOST: https://vault.punchh.com
      BUILD_NUMBER: "1"

    livenessProbe:
      initialDelaySeconds: 90
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 45
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5

    podSecurityContext: {}
    securityContext: {}


jbapi:
  name: jbapi
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    GO_ENV: production
    SNOWFLAKE_DB: DATA_ENGINEERING_PRODUCTION
    SNOWFLAKE_SCHEMA: dairyqueen
    JB_INTERNAL_PORT: :50051
    DASHBOARD_SERVICE_HOST: campaigns.dairyqueen:9093

  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 512m
      memory: 512Mi

jbapigateway:
  name: jbapigateway
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    GO_ENV: production
    CORS_ALLOW_ORIGIN: https://dashboarddq.punchh.com
    JWT_KEY: ""
    GRPC_HOST_PORT: jbapi.dairyqueen:80
    DASHBOARD_SERVICE_HOST: campaigns.dairyqueen:9093

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 256m
      memory: 256Mi

campaigns:
  name: campaigns
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    ENABLE_GRPC: True
    GRPC_POOL_SIZE: 24
    GRPC_PORT: 9093
    RACK_ENV: production
    RAILS_ENV: production
    SERVICE_TYPE: CapaignRewardGRPC

  resources:
    limits:
      cpu: 2048m
      memory: 4096Mi
    requests:
      cpu: 1536m
      memory: 2048Mi

messaging:
  name: messaging
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    GRPC_POOL_SIZE: 24
    GRPC_PORT: 9092
    RACK_ENV: production
    RAILS_ENV: production
    NEWRELIC_APP_NAME: Dairyqueen Messaging Service
    RAILS_MAX_THREADS: 10

  resources:
    limits:
      cpu: 1024m
      memory: 2048Mi
    requests:
      cpu: 1024m
      memory: 2048Mi

jbinternalapi:
  name: jbinternalapi
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    GO_ENV: production
    SNOWFLAKE_DB: DATA_ENGINEERING_PRODUCTION
    SNOWFLAKE_SCHEMA: dairyqueen
    JB_INTERNAL_PORT: :9091
    ENABLE_GRPC: True
    GRPC_POOL_SIZE: 5

  resources:
    limits:
      cpu: 2048m
      memory: 1536Mi
    requests:
      cpu: 2048m
      memory: 1024Mi

jbmessagingrest:
  name: jbmessagingrest
  pdbMaxUnAvailable: 20%
  replicaCount: 2
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    RACK_ENV: production
    RAILS_ENV: production

  resources:
    limits:
      cpu: 2048m
      memory: 1536Mi
    requests:
      cpu: 2048m
      memory: 1024Mi

jbdashboardrest:
  name: jbdashboardrest
  pdbMaxUnAvailable: 20%
  replicaCount: 2
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    ENABLE_APIS_FOR_INTERNAL_LOAD_BALANCER: True
    RACK_ENV: production
    RAILS_ENV: production
    ENABLE_RAILS: True
    NEWRELIC_APP_NAME: "Dairyqueen Internal Dashboard API"
    SERVICE_TYPE: Web
    UNICORN_TIMEOUT: 60
    UNICORN_WORKER_PROCESSES: 10

  resources:
    limits:
      cpu: 3072m
      memory: 7168Mi
    requests:
      cpu: 3072m
      memory: 6144Mi

userfeaturesinternal:
  name: userfeaturesinternal
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    GO_ENV: production
    SNOWFLAKE_DB: DATA_ENGINEERING_PRODUCTION
    SNOWFLAKE_SCHEMA: dairyqueen

  resources:
    limits:
      cpu: 1024m
      memory: 1024Mi
    requests:
      cpu: 1024m
      memory: 512Mi

jbredemptionsprocessor:
  name: jbredemptionsprocessor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: REDEMPTIONS
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: dairyqueen.punchh_server.redemptions.honor
    NEW_RELIC_APP_NAME: jb-redemptions-processor
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 128Mi

jbworkerpool:
  name: jbworkerpool
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CADENCE_HOST: cadence.punchh.internal:7933
    CASSANDRA_HOST: cassandra.punchh.internal
    DASHBOARD_SERVICE_HOST: campaigns.dairyqueen:9093
    ENVIRONMENT: production
    KAFKA_HOST: kafka-broker-1.punchh.internal:9092
    KAFKA_TOPIC: dairyqueen.jb.events
    MESSAGING_SERVICE_HOST: messaging.dairyqueen:9092
    NEW_RELIC_APP_NAME: jb-workerpool-service
    REGISTRY_HOST: http://kafka-schema-registry.punchh.internal
    USER_FEATURES_SERVICE_HOST: userfeaturesinternal.dairyqueen:80
    ELASTIC_SEARCH_SERVICE_HOST: https://vpc-dairyqueen-elasticsearch-dzh5ehiyijx27epm5m2vtqgeg4.us-west-2.es.amazonaws.com

  resources:
    limits:
      cpu: 3072m
      memory: 4096Mi
    requests:
      cpu: 3072m
      memory: 2048Mi

jbcampaignprocessor:
  name: jbcampaignprocessor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: CAMPAIGN
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: dairyqueen.punchh_server.user_campaigns
    NEW_RELIC_APP_NAME: jb-campaign-processor
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 128Mi

jbemailprocessor:
  name: jbemailprocessor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: EMAIL
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: sendgrid-events-webhook
    NEW_RELIC_APP_NAME: jb-email-processor
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 2048m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1536Mi

jbemailprocessormarketing:
  name: jbemailprocessormarketing
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: EMAIL
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: sendgrid-events-marketing
    NEW_RELIC_APP_NAME: jb-email-processor-marketing
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 2048m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1536Mi

jbemailprocessortransactional:
  name: jbemailprocessortransactional
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: EMAIL
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: sendgrid-events-transactional
    NEW_RELIC_APP_NAME: jb-email-processor-transactional
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 2048m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1536Mi

gokafkaemailsubreactor:
  name: gokafkaemailsubreactor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: emailsub
    GO_ENV: production
    KAFKA_GROUP: emailsub
    KAFKA_TOPIC: sendgrid-events-marketing
    SCHEMA_REGISTRY_URL: http://kafka-schema-registry.punchh.internal
    TRANSIENT_RETRY_INTERVAL: 60s
    TRANSIENT_RETRY_ATTEMPTS: 3
    WEBHOOK_SVC_URL: https://hooksdq.punchh.com/incoming_webhooks/sendgrid
    NEW_RELIC_APP_NAME: go-kafka-emailsub-reactor
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 2048m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1536Mi

jbsignupprocessor:
  name: jbsignupprocessor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: SIGNUP
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: dairyqueen.punchh_server.users
    NEW_RELIC_APP_NAME: jb-signup-processor
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 128Mi

jbpurchaseprocessor:
  name: jbpurchaseprocessor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: PURCHASE
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: dairyqueen.punchh_server.checkins
    NEW_RELIC_APP_NAME: jb-purchase-processor
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 128Mi

jbcouponsprocessor:
  name: jbcouponsprocessor
  pdbMaxUnAvailable: 20%
  replicaCount: 3
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CACHE_TIMEOUT: 60s
    CONSUMER_TYPE: COUPONS
    GO_ENV: production
    KAFKA_GROUP: JB
    KAFKA_TOPIC: dairyqueen.punchh_server.user_coupon_redemptions
    NEW_RELIC_APP_NAME: jb-coupons-processor
    DASHBOARD_SVC_URL: campaigns.dairyqueen:9093
    USER_FEATURES_SVC_URL: userfeaturesinternal.dairyqueen:80
    KAFKA_URL: "kafka-broker-1.punchh.internal:9092,kafka-broker-2.punchh.internal:9092,kafka-broker-3.punchh.internal:9092"

  resources:
    limits:
      cpu: 2048m
      memory: 2048Mi
    requests:
      cpu: 2048m
      memory: 1536Mi

jbschemamigration:
  name: jbschemamigration
  pdbMaxUnAvailable: 20%
  replicaCount: 1
  maxSurge: 80%
  maxUnavailable: 20%

  env:
    CASSANDRA_URL: cassandra.punchh.internal
    SNOWFLAKE_DB: DATA_ENGINEERING_PRODUCTION
    GO_ENV: production
    SNOWFLAKE_SCHEMA: dairyqueen
    CASSANDRA_KEYSPACE: jb

  resources:
    limits:
      cpu: 256m
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 128Mi

campaignshowpage:
  initcontainer:
    env:
      global_secrets_arn: "arn:aws:secretsmanager:us-east-1:060724984176:secret:dairyqueen/campaign-show-page-iPwgcI"
      tenant_secrets_arn: "arn:aws:secretsmanager:us-east-1:060724984176:secret:dairyqueen/campaign-show-page-iPwgcI"
      service_secrets_arn: "arn:aws:secretsmanager:us-east-1:060724984176:secret:dairyqueen/campaign-show-page-iPwgcI"
      db_secrets_arn: "arn:aws:secretsmanager:us-east-1:060724984176:secret:dairyqueen/db-secrets-DstdPM"

  name: campaignshowpage
  pdbMaxUnAvailable: 20%
  replicaCount: 2
  maxSurge: 80%
  maxUnavailable: 20%
  serviceaccount: secrets-manager
  pdb: true
  kindofcomponent: api
  healthCheckPath: /healthz
  containerPort: 8080
  args: ["source /tmp/secret && ./server"]
  sidecar: false
  antiaffinity: false
  node_group_type: web

  env:
    AWS_REGION: us-west-2
    ENVIRONMENT: production
    CREDENTIAL_PROVIDER: secret_manager

  healthcheck:
    enabled: true
  service:
    enabled: true
    restapi: true
  resources:
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 250m
      memory: 500Mi

images:
  campaigns: punchh/shippable
  jbapi: punchh/jb-api
  jbapigateway: punchh/jb-api-gateway
  messaging: punchh/shippable-messaging-service
  jbinternalapi: punchh/jb-api
  jbmessagingrest: punchh/shippable-messaging-service
  jbdashboardrest: punchh/shippable
  userfeaturesinternal: punchh/common_user_features
  jbredemptionsprocessor: punchh/jb-event-processor
  jbworkerpool: punchh/jb-workerpool-service
  jbcampaignprocessor: punchh/jb-event-processor
  jbemailprocessor: punchh/jb-event-processor
  jbsignupprocessor: punchh/jb-event-processor
  jbpurchaseprocessor: punchh/jb-event-processor
  jbcouponsprocessor: punchh/jb-event-processor
  campaignshowpage: punchh/csp-foundation
  jbemailprocessormarketing: punchh/jb-event-processor
  jbemailprocessortransactional: punchh/jb-event-processor
  gokafkaemailsubreactor: punchh/go-kafka-reactor
