apiVersion: apps/v1
kind: Deployment
metadata:
  name: merlin-web
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: api
spec:
  replicas: {{ .Values.merlinweb.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.merlinweb.maxSurge }}
      maxUnavailable: {{ .Values.merlinweb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/part-of: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: api
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.common.imagePullSecrets }}
      serviceAccountName: secrets-manager
      securityContext:
        {{- toYaml .Values.global.common.podSecurityContext | nindent 8 }}
      initContainers:
        - name: awscli-secret-manager
          image: docker.io/punchh/init-container-secrets-manager:v1
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:
            - name: init-config
              mountPath: /tmp/
            - name: secret-vol
              mountPath: /mnt/
          env:
{{- range $key, $value := .Values.merlinweb.initcontainer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
      containers:
        - name: {{ .Values.merlinweb.name }}
          securityContext:
            {{- toYaml .Values.global.common.securityContext | nindent 12 }}
          image: {{ .Values.images.merlinweb }}:{{ .Values.tags.merlinweb }}
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          volumeMounts:
            - name: secret-vol
              mountPath: /tmp/
          ports:
            - name: app
              containerPort: 50051
              protocol: TCP
          resources:
            {{- toYaml .Values.merlinweb.resources | nindent 12 }}
          env:
{{- range $key, $value := .Values.global.common.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.merlinweb.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: VAULT_TOKEN
      volumes:
        - name: init-config
          configMap:
            name: merlin
        - name: secret-vol
          emptyDir:
            medium: Memory
