apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
  labels:
    app: schemaregistry
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: schemaregistry
  