{{- if .Values.emailtemplate.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-emailtemplate
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: emailtemplate
  minReplicas: 1
  maxReplicas: {{ .Values.emailtemplate.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.emailtemplate.hpa.type }}
      targetAverageUtilization: {{ .Values.global.common.hpa.targetAverageUtilization }}
{{ end }}
