apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datalake-airflow-worker
spec:
  selector:
    matchLabels:
      app: datalake-airflow-worker
  serviceName: datalake-airflow-worker-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: datalake-airflow-worker
    spec:
      containers:
      - name: {{ .Values.datalake.worker.name }}
        image: {{ .Values.images.airflow }}:{{ index .Values.tags "datalake-airflow" }}
        args: [ {{ .Values.datalake.worker.args | quote }} ]
        imagePullPolicy: {{ .Values.global.common.pullPolicy }}
        ports:
          - name: {{ .Values.datalake.worker.name }}
            containerPort: {{ .Values.datalake.worker.port }}
            protocol: TCP
        resources:
            {{- toYaml .Values.datalake.worker.resources | nindent 10 }}
        env:
{{- range $key, $value := .Values.global.common.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.datalake.worker.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: {{ .Values.global.common.env.db_con1 }}://{{ .Values.global.common.env.DB_USER }}:{{ .Values.global.common.env.DB_PASSWORD }}@{{ .Values.global.common.env.DB_HOST }}:5432/{{ .Values.global.common.env.DB_NAME_AIRFLOW }}
        - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
          value: {{ .Values.global.common.env.db_con2 }}://{{ .Values.global.common.env.DB_USER }}:{{ .Values.global.common.env.DB_PASSWORD }}@{{ .Values.global.common.env.DB_HOST }}:5432/{{ .Values.global.common.env.DB_NAME_AIRFLOW }}
        - name: REDIS_HOST
          value: datalake-airflow-redis-svc.{{ .Release.Namespace }}
        volumeMounts:
          - mountPath: /usr/local/airflow/dags
            name: efs-share
      volumes:
      - name: efs-share
        persistentVolumeClaim:
          claimName: efs-claim
