apiVersion: v1
kind: Service
metadata:
  name: datalake-airflow-flower-svc
  labels:
    app: datalake-airflow-flower-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.common.service.port }}
      targetPort: {{ .Values.datalake.flower.port }}
      protocol: TCP
      name: flower
  selector:
    app: datalake-airflow-flower
