apiVersion: v1
kind: Service
metadata:
  name: datalake-airflow-worker-svc
  labels:
    app: datalake-airflow-worker-svc
spec:
  ports:
  - port: {{ .Values.global.common.service.port }}
    targetPort: {{ .Values.datalake.worker.port }}
    protocol: TCP
    name: worker
  selector:
    app: datalake-airflow-worker
  clusterIP: None
