apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaignshowpage
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: api
spec:
  replicas: {{ .Values.campaignshowpage.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.campaignshowpage.maxSurge }}
      maxUnavailable: {{ .Values.campaignshowpage.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/part-of: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: api
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.common.imagePullSecrets }}
      serviceAccountName: secrets-manager
      securityContext:
        {{- toYaml .Values.global.common.podSecurityContext | nindent 8 }}
      initContainers:
        - name: awscli-secret-manager
          image: docker.io/punchh/init-container-secrets-manager:v2
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          command:
          - bash
          - /tmp/init.sh
          volumeMounts:
          - name: secret-vol
            mountPath: /mnt/
          env:
{{- range $key, $value := .Values.campaignshowpage.initcontainer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
      containers:
        - name: {{ .Values.campaignshowpage.name }}
          securityContext:
            {{- toYaml .Values.global.common.securityContext | nindent 12 }}
          image: {{ .Values.images.campaignshowpage }}:{{ .Values.tags.campaignshowpage }}
          command:
            - /bin/sh
          args:
            - '-c'
            - source /tmp/secret && ./server
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          volumeMounts:
          - name: secret-vol
            mountPath: /tmp/
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.livenessProbe.successThreshold }}
          resources:
            {{- toYaml .Values.campaignshowpage.resources | nindent 12 }}
          env:
{{- range $key, $value := .Values.global.common.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.campaignshowpage.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
      volumes:
        - name: secret-vol
          emptyDir:
            medium: Memory
