{{- if .Values.jbapi.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-jbapi
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: jbapi
  minReplicas: 1
  maxReplicas: {{ .Values.jbapi.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.jbapi.hpa.type }}
      targetAverageUtilization: {{ .Values.global.common.hpa.targetAverageUtilization }}
{{ end }}
