{{- range $service := (list "frontend" "history" "matching" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cadence.componentname" (list $ $service) }}
  labels:
    app.kubernetes.io/name: {{ include "cadence.name" $ }}
    helm.sh/chart: {{ include "cadence.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: {{ $service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  replicas: {{ default $.Values.server.replicaCount $serviceValues.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cadence.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cadence.name" $ }}
        helm.sh/chart: {{ include "cadence.chart" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: {{ $service }}
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmap.yaml") $ | sha256sum }}
        {{- with (default $.Values.server.podAnnotations $serviceValues.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml (default $.Values.server.podSecurityContext $serviceValues.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $service }}
          securityContext:
            {{- toYaml (default $.Values.server.securityContext $serviceValues.securityContext) | nindent 12 }}
          image: "{{ $.Values.server.image.repository }}:{{ $.Values.server.image.tag }}"
          imagePullPolicy: {{ $.Values.server.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICES
              value: {{ $service }}
            - name: CADENCE_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cadence.persistence.secretName" (list $ "default") }}
                  key: {{ include "cadence.persistence.secretKey" (list $ "default") }}
            - name: CADENCE_VISIBILITY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cadence.persistence.secretName" (list $ "visibility") }}
                  key: {{ include "cadence.persistence.secretKey" (list $ "visibility") }}
          ports:
            - name: rpc
              containerPort: {{ include (printf "cadence.%s.internalPort" $service) $ }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 150
            tcpSocket:
              port: rpc
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: rpc
          volumeMounts:
            - name: config
              mountPath: /etc/cadence/config/config_template.yaml
              subPath: config_template.yaml
            - name: config
              mountPath: /etc/cadence/config/dynamicconfig/config.yaml
              subPath: dynamic_config.yaml
          resources:
            {{- toYaml (default $.Values.server.resources $serviceValues.resources) | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cadence.fullname" $ }}
---
{{- end }}
