apiVersion: v1
kind: Service
metadata:
  name: menus
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version  }}
    app.kubernetes.io/part-of: api
spec:
  type: {{ .Values.global.common.service.type }}
  ports:
    - port: {{ .Values.global.common.service.port }}
      targetPort: app
      protocol: TCP
      name: http
      port: 80
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version  }}
    app.kubernetes.io/part-of: api
