{{- if .Values.punchhcommon.pdb }}

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: punchhcommon
  annotations:
    helm.sh/hook: "post-upgrade, post-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }} 
    app.kubernetes.io/part-of: {{ .Values.punchhcommon.kindofcomponent }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }} 
      app.kubernetes.io/part-of: {{ .Values.punchhcommon.kindofcomponent }}
  maxUnavailable: {{ .Values.punchhcommon.pdbMaxUnAvailable }}

{{ end }}