apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbmessagingrest
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: api
spec:
  replicas: {{ .Values.jbmessagingrest.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.jbmessagingrest.maxSurge }}
      maxUnavailable: {{ .Values.jbmessagingrest.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/part-of: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: api
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.common.imagePullSecrets }}
    {{- if .Values.global.common.serviceAccount.create }}
      serviceAccountName: jbmessagingrest
    {{- end }}
      securityContext:
        {{- toYaml .Values.global.common.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: punchh/k8s-nginx:2.0.0
          resources:
            limits:
              cpu: 256m
              memory: 256Mi
            requests:
              cpu: 256m
              memory: 256Mi
          ports:
           - name: nginx
             containerPort: 80
        - name: {{ .Values.jbmessagingrest.name }}
          securityContext:
            {{- toYaml .Values.global.common.securityContext | nindent 12 }}
          image: {{ .Values.images.jbmessagingrest }}:{{ .Values.tags.jbmessagingrest }}
          imagePullPolicy: {{ .Values.global.common.pullPolicy }}
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.global.common.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.common.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.global.common.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.global.common.livenessProbe.successThreshold }}
          resources:
            {{- toYaml .Values.jbmessagingrest.resources | nindent 12 }}
          env:
{{- range $key, $value := .Values.global.common.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := .Values.jbmessagingrest.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
            - name: AIRBRAKE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: AIRBRAKE_PROJECT_ID
            - name: AIRBRAKE_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: AIRBRAKE_PROJECT_KEY
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: ENCRYPTION_KEY
            - name: GRPC_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: GRPC_CREDENTIAL
            - name: MASTER_DB_URL
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: MASTER_DB_URL
            - name: NEWRELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: NEWRELIC_LICENSE_KEY
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: SECRET
            - name: SLAVE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: stack-credentials
                  key: SLAVE_DB_URL
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: VAULT_TOKEN
      nodeSelector:
        node_group_type: web
