apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version  }}
    app.kubernetes.io/part-of: api
spec:
  type: {{ .Values.global.common.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.global.common.service.port }}
      targetPort: 9092
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version  }}
    app.kubernetes.io/part-of: api
